# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

language: cpp

compiler:
    - g++

notifications:
    email:
        recipients:
            - tim.albring@scicomp.uni-kl.de
  
branches:
    only:
        - feature_AD

env:
    global:
        CXXFLAGS=-O3
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./preconfigure.py --install=$TRAVIS_BUILD_DIR --enable-reverse=CODI"
          TEST_SCRIPT=serial_regression.py
        # Parallel build and test
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi -p "--with-cc=mpicc --with-cxx=mpicxx" --install=$TRAVIS_BUILD_DIR"
          TEST_SCRIPT=parallel_regression.py

before_install:
    # install the necessary packages
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy mpich2
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
    - echo $TRAVIS_BUILD_DIR
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    - make -j 8
    - make install

    # Add environmental variables according to the configure step
    - export SU2_RUN=$TRAVIS_BUILD_DIR/bin
    - export SU2_HOME=$TRAVIS_BUILD_DIR
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Get the test cases
    - git clone https://github.com/su2code/TestCases.git ./TestData
    - cd TestData/
    - git checkout develop
    # Go back to SU2 root and copy the test data into the folder structure
    - cd $TRAVIS_BUILD_DIR
    - cp -R ./TestData/* ./TestCases/
    # Enter the SU2/TestCases/ directory, which is now ready to run
    - cd TestCases/

script:
    # run the tests
    python $TEST_SCRIPT


