# Continous Integration setup for SU2.
# Tests on the develop branch in both serial and parallel.

language: cpp

compiler:
    - g++

notifications:
    email:
        recipients:
            - su2code-dev@lists.stanford.edu
  
branches:
    only:
        - develop

env:
    global:
        CXXFLAGS="-O3 -Wall -Wextra -Wno-unused-parameter -Wno-empty-body"
    matrix:
        # Serial build and test
        - CONFIGURE_COMMAND="./preconfigure.py --prefix=$TRAVIS_BUILD_DIR --enable-autodiff"
          TEST_SCRIPT=serial_regression.py
        # Parallel build and test
        - CONFIGURE_COMMAND="./preconfigure.py --enable-mpi --with-cc=mpicc --with-cxx=mpicxx --prefix=$TRAVIS_BUILD_DIR --enable-autodiff"
          TEST_SCRIPT=parallel_regression.py

before_install:
    # install the necessary packages
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-numpy mpich2
    # the default g++ in travis is g++-4.6, we need at least 4.7 for some c++11 features
    - sudo apt-get install -qq g++-4.8
    - export CXX="g++-4.8" CC="gcc-4.8"
    - export MPICH_CXX=$CXX MPICH_CC=$CC  

install:
    - echo $TRAVIS_BUILD_DIR
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND
    - make -j 4
    - make install

    # Add environmental variables according to the configure step
    - export SU2_RUN=$TRAVIS_BUILD_DIR/bin
    - export SU2_HOME=$TRAVIS_BUILD_DIR
    - export PATH=$PATH:$SU2_RUN
    - export PYTHONPATH=$PYTHONPATH:$SU2_RUN

before_script:
    # Get the test cases
    - git clone https://github.com/su2code/TestCases.git ./TestData
    - cd TestData/
    - git checkout develop
    # Go back to SU2 root and copy the test data into the folder structure
    - cd $TRAVIS_BUILD_DIR
    - cp -R ./TestData/* ./TestCases/
    # Enter the SU2/TestCases/ directory, which is now ready to run
    - cd TestCases/

script:
    # run the tests
    python $TEST_SCRIPT


